#!/usr/bin/env bash
# Seed the repo with backlog issues. Run once after `gh repo create`.
set -euo pipefail

REPO="${REPO:-$(gh repo view --json nameWithOwner --jq .nameWithOwner)}"

# Create the labels we use.
for spec in \
  'hardening|d73a4a|Security or operational hardening' \
  'verify|0e8a16|Has a verification script the orchestrator should run' \
  'k3s|c5def5|hummingbird-k3s VM' \
  'k8s|c5def5|hummingbird-k8s VM' \
  'worker|c5def5|hummingbird-k8s-worker VM' \
  'ci|fbca04|CI / GitHub Actions' \
  'docs|0075ca|Documentation' \
  ; do
  IFS='|' read -r name color desc <<<"$spec"
  gh label create "$name" --color "$color" --description "$desc" --repo "$REPO" 2>/dev/null || \
  gh label edit   "$name" --color "$color" --description "$desc" --repo "$REPO"
done

issue() {
  local title="$1"; shift
  local labels="$1"; shift
  local body="$*"
  gh issue create --repo "$REPO" --title "$title" --label "$labels" --body "$body"
}

issue "Rename hummingbird VM to hummingbird-k3s" "k3s" \
"The current k3s VM on the KVM host is still under the legacy name \`hummingbird\`. Run \`sudo bash redo.sh\` once and verify the new domain name shows up in Cockpit."

issue "Drop hardcoded sudo password from build scripts" "hardening,k3s,k8s,worker" \
"\`build*.sh\` bake \`1234asdf\` as the sudo password via \`bib-config.toml\`. Switch to SSH-key-only (drop \`password =\` from the bib config) and require explicit key auth."

issue "Disable sshd password authentication in images" "hardening" \
"Drop a \`/etc/ssh/sshd_config.d/99-no-password.conf\` with \`PasswordAuthentication no\` and \`ChallengeResponseAuthentication no\` into every flavor's Containerfile."

issue "Enable bootc-fetch-apply-updates timer in images" "hardening,verify" \
"All flavors. \`ln -sf /usr/lib/systemd/system/bootc-fetch-apply-updates.timer /etc/systemd/system/timers.target.wants/bootc-fetch-apply-updates.timer\` in the Containerfiles. Verify: timer is active after fresh boot."

issue "Sign published images with cosign" "hardening,ci" \
"Add a cosign signing step to \`.github/workflows/build-images.yml\`. Use OIDC keyless signing for ghcr.io image refs. Configure bootc/podman policy on consumers to verify."

issue "Swap flannel for Cilium (NetworkPolicy support)" "hardening,k8s,verify" \
"Flannel has no NetworkPolicy enforcement. Replace with Cilium (eBPF datapath + Hubble) or Calico. Update \`k8s-init.sh\` to apply Cilium manifests instead of \`kube-flannel.yml\`. Verify: \`kubectl apply\` a deny-all policy and confirm a test pod can no longer reach DNS."

issue "Default PodSecurity admission to restricted" "hardening,k8s" \
"Add \`--admission-control-config-file\` to the kubeadm config so the cluster-wide default is the \`restricted\` Pod Security Standard. \`kube-system\` namespace stays \`privileged\`."

issue "Enable etcd encryption at rest" "hardening,k8s,verify" \
"Add an \`EncryptionConfiguration\` and the \`--encryption-provider-config\` apiserver flag via kubeadm InitConfiguration. Verify: \`etcdctl get /registry/secrets/...\` shows ciphertext, not plain values."

issue "Per-VM short-TTL kubeadm join tokens for workers" "hardening,worker" \
"Today \`build-worker.sh\` bakes a \`--ttl 0\` (never expires) token into every worker image. Switch to per-VM tokens generated by \`spawn-workers.sh\` at spawn time, passed via cloud-init or a per-VM \`COPY\`."

issue "Run kube-bench and fix high-severity findings" "hardening,k8s,verify" \
"Deploy aquasec/kube-bench job in the cluster, capture output as the baseline, then close each high finding individually."

issue "HA control plane: 3 CPs + keepalived/haproxy VIP" "k8s,verify" \
"Add a \`ROLE=cp\` variant of \`Containerfile.k8s\` that also installs keepalived+haproxy, configured to front a VIP (e.g. 192.168.122.10). First CP runs \`kubeadm init --control-plane-endpoint=<vip>:6443 --upload-certs\`. Workers + subsequent CPs point at the VIP. Verify: kill one CP, cluster keeps working."

issue "End-to-end bootc upgrade test" "verify,k3s,k8s,worker" \
"Spin a VM from \`ghcr.io/<OWNER>/hummingbird-<flavor>:vA\`, push \`:vB\` to GHCR, run \`bootc upgrade && systemctl reboot\` in the guest, confirm the new digest is the booted deployment and that k3s/kubelet are still healthy."

issue "Apiserver audit logging" "hardening,k8s" \
"Drop an \`audit-policy.yaml\` and pass \`--audit-policy-file\` + \`--audit-log-path\` via the kubeadm config. Logs to \`/var/log/k8s-audit.log\`, mounted as a HostPath."

issue "Self-hosted GitHub runner on a KVM host for orchestrator + upgrade tests" "ci" \
"Register a KVM-capable machine as a self-hosted runner so workflows that need real KVM (orchestrator, e2e upgrade test) can run. Document the registration command + service unit."

issue "Orchestrator workflow: iterate open 'verify' issues and run each issue's test script" "ci" \
"\`.github/workflows/orchestrator.yml\`. Triggered nightly + workflow_dispatch. For each open issue labeled \`verify\`, look up a script under \`tests/issue-<n>.sh\`, run it on the self-hosted runner, post pass/fail back to the issue as a comment."

issue "Document repository structure + per-image build flow in README" "docs" \
"Flesh out README with a section per script, a topology diagram (CP + N workers), and the GHCR consumption story (\`bootc switch ghcr.io/.../hummingbird-k3s:vX\`)."
